create table public.messages (
  id bigint generated by default as identity primary key,
  text text not null,
  name text not null default 'anonymous',
  status text not null default 'review'
    check (status in ('approved', 'review', 'rejected')),
  created_at timestamptz not null default now()
);

create index messages_status_created_idx
on public.messages(status, created_at desc);

alter table public.messages enable row level security;
